# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e42d68374d4727542b01079422eb00527364b2883502444813cab6bb389324f76fe6a5a7d63778909e1b80fa03054a2b29ef2f3806c905e985fa3dca8b3941c0

test:
  secret_key_base: ea27685575c79447527ba00edcf1ed87949b3895a1b655099258a9e38bda9801678ceecce34e55647e1ace7b0fc541ecef51683ead6ba8d880640d05367b525f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
